[package]
name = "old_faithful_learn"
version = "0.1.0"
authors = ["patrickvonplaten <patrick.v.platen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
